### ISSUE TITLE
Grand Design Renewal

### ISSUE THREAD

**Issue by angdev** [HwaYo/parrot#40]
#39

아직 할 일이 많습니다.
- [x] medium text editor로 작성된 노트 저장 (#19)
- [x] Control Panel (책갈피, 배속, ...) (#44)
- [x] 타이틀 medium h3, b 적용한 것처럼 css 적용하기
- [x] 녹음 리스트의 "My record list" 스타일 변경하기
- [x] 음파 fixed? (#45)
- [x] 새 녹음 페이지에서 음파 부분이 비어보이는 문제 (#46)
- [x] 죄수번호 humanize
